/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SurahsRouteImport } from './routes/surahs'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RecitationsRouteImport } from './routes/recitations'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SurahSlugRouteImport } from './routes/surah/$slug'
import { Route as ApiArchiveSplatRouteImport } from './routes/api/archive/$'
import { Route as AdminRecordingsNewRouteImport } from './routes/admin/recordings/new'

const SurahsRoute = SurahsRouteImport.update({
  id: '/surahs',
  path: '/surahs',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RecitationsRoute = RecitationsRouteImport.update({
  id: '/recitations',
  path: '/recitations',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SurahSlugRoute = SurahSlugRouteImport.update({
  id: '/surah/$slug',
  path: '/surah/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArchiveSplatRoute = ApiArchiveSplatRouteImport.update({
  id: '/api/archive/$',
  path: '/api/archive/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecordingsNewRoute = AdminRecordingsNewRouteImport.update({
  id: '/recordings/new',
  path: '/recordings/new',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRoute
  '/recitations': typeof RecitationsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/surahs': typeof SurahsRoute
  '/surah/$slug': typeof SurahSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/recordings/new': typeof AdminRecordingsNewRoute
  '/api/archive/$': typeof ApiArchiveSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/recitations': typeof RecitationsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/surahs': typeof SurahsRoute
  '/surah/$slug': typeof SurahSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/recordings/new': typeof AdminRecordingsNewRoute
  '/api/archive/$': typeof ApiArchiveSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRoute
  '/recitations': typeof RecitationsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/surahs': typeof SurahsRoute
  '/surah/$slug': typeof SurahSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/recordings/new': typeof AdminRecordingsNewRoute
  '/api/archive/$': typeof ApiArchiveSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/recitations'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/surahs'
    | '/surah/$slug'
    | '/admin/'
    | '/admin/recordings/new'
    | '/api/archive/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/recitations'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/surahs'
    | '/surah/$slug'
    | '/admin'
    | '/admin/recordings/new'
    | '/api/archive/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/recitations'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/surahs'
    | '/surah/$slug'
    | '/admin/'
    | '/admin/recordings/new'
    | '/api/archive/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRoute
  RecitationsRoute: typeof RecitationsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SurahsRoute: typeof SurahsRoute
  SurahSlugRoute: typeof SurahSlugRoute
  ApiArchiveSplatRoute: typeof ApiArchiveSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/surahs': {
      id: '/surahs'
      path: '/surahs'
      fullPath: '/surahs'
      preLoaderRoute: typeof SurahsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recitations': {
      id: '/recitations'
      path: '/recitations'
      fullPath: '/recitations'
      preLoaderRoute: typeof RecitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/surah/$slug': {
      id: '/surah/$slug'
      path: '/surah/$slug'
      fullPath: '/surah/$slug'
      preLoaderRoute: typeof SurahSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/archive/$': {
      id: '/api/archive/$'
      path: '/api/archive/$'
      fullPath: '/api/archive/$'
      preLoaderRoute: typeof ApiArchiveSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/recordings/new': {
      id: '/admin/recordings/new'
      path: '/recordings/new'
      fullPath: '/admin/recordings/new'
      preLoaderRoute: typeof AdminRecordingsNewRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminRecordingsNewRoute: typeof AdminRecordingsNewRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminRecordingsNewRoute: AdminRecordingsNewRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRoute,
  RecitationsRoute: RecitationsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SurahsRoute: SurahsRoute,
  SurahSlugRoute: SurahSlugRoute,
  ApiArchiveSplatRoute: ApiArchiveSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
